#!/usr/bin/env python3
"""generate_reflection.py - runs discover_reflectable.py then reflectgen.py
in a single step, always using fresh discovery results rather than ones
computed once at CMake configure time - see cmake/ReflectGen.cmake for why:
CMake's build graph (a custom command's COMMAND/DEPENDS) is fixed at
configure time, so a build-time-only discovery pass has no way to hand its
*results* to a separately-configured generation step within the same
build - the two have to run as one command instead, every time anything
that could change the answer might have (this script's own --scan-dir
trees' *candidates*, tracked at the CMake level via a glob's own
CONFIGURE_DEPENDS - see that file - not by this script).

This is what lets adding an "@reflect"/NEWUI_REFLECT_PRIVATE() marker to a
header that's *already* part of the build be picked up by an ordinary
rebuild, no manual CMake reconfigure needed - only a brand new file (one
CMake doesn't know to depend on yet) still needs one.

Usage:
    python generate_reflection.py --python <python.exe> --scan-dir <dir> [--scan-dir <dir>...]
        --output <output.cpp> [--require-marker] [--clang-arg <arg>...]
"""

import argparse
import os
import re
import subprocess
import sys
import time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# discover_reflectable.py always writes exactly one line of the form
# `set(VAR "path1" "path2" ...)` (see its own main()) - extracting every
# quoted string is enough, no real CMake parser needed for output this
# constrained.
_QUOTED_RE = re.compile(r'"([^"]*)"')


def read_cmake_list(path):
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    return _QUOTED_RE.findall(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--python", required=True, help="python executable to invoke both sub-scripts with")
    parser.add_argument("--scan-dir", action="append", required=True, dest="scan_dirs",
                         help="directory to scan (repeatable)")
    parser.add_argument("-o", "--output", required=True, help="final generated .cpp path")
    parser.add_argument("--require-marker", action="store_true",
                         help="forwarded to discover_reflectable.py - see its own --help")
    parser.add_argument("--clang-arg", action="append", default=[], dest="clang_args",
                         help="forwarded to reflectgen.py after its own '--' (repeatable)")
    args = parser.parse_args()

    run_start = time.perf_counter()

    output_dir = os.path.dirname(os.path.abspath(args.output))
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    headers_cmake = args.output + ".headers.cmake"

    discover_cmd = [
        args.python, os.path.join(SCRIPT_DIR, "discover_reflectable.py"),
        *args.scan_dirs, "-o", headers_cmake,
    ]
    if args.require_marker:
        discover_cmd.append("--require-marker")
    subprocess.run(discover_cmd, check=True)

    headers = read_cmake_list(headers_cmake)

    if not headers:
        # reflectgen.py requires at least one input file (argparse
        # nargs="+") - write the same "nothing to register" placeholder
        # its own generate() would produce for zero classes/enums instead,
        # matching what cmake/ReflectGen.cmake's own empty-case fallback
        # used to do directly (now handled here instead, since this
        # script is the one that knows the discovery result).
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(
                "// Generated by reflectgen (tools/reflectgen) - see tools/reflectgen/README.md.\n"
                "//\n"
                f"// No reflectable headers found under {', '.join(args.scan_dirs)}.\n"
            )
        print(f"generate_reflection: no reflectable headers found - wrote placeholder {args.output} "
              f"in {time.perf_counter() - run_start:.2f}s")
        return

    include_args = []
    for h in headers:
        include_args += ["--include", h]

    reflectgen_cmd = [args.python, os.path.join(SCRIPT_DIR, "reflectgen.py"), *headers, "-o", args.output, *include_args]
    if args.clang_args:
        reflectgen_cmd.append("--")
        reflectgen_cmd += args.clang_args
    subprocess.run(reflectgen_cmd, check=True)

    print(f"generate_reflection: done in {time.perf_counter() - run_start:.2f}s total")


if __name__ == "__main__":
    main()
