// mvc1 - a minimal, real, end-to-end MVC demo: two Models (StringListModel/
// StringTreeModel) driving a ListView and a TreeView (controls.h) via
// ListController/TreeController - the same Model/Controller/Item
// foundation items-plan.md (repo root) asked for, exercised on screen: a
// real scrollable, clickable list and a real expandable, clickable tree.
// See HANDOFF.md Parts 58-64 for the implementation history behind
// ListView/TreeView/ListController/TreeController/ListItem/TreeItem/
// Model::size()/TreeModel::childCount().

#include "newui/newui.h"
#include "newui/application.h"
#include "newui/controls.h"
#include "newui/frame.h"
#include "newui/layout.h"
#include "newui/models.h"
#include "newui/reflection.h"
#include "newui/rootview.h"
#include "newui/subview.h"
#include "newui/uicolormanager.h"
#include "newui/view.h"
#include "newui/viewstyle.h"

#include <any>
#include <cstdio>
#include <iostream>
#include <map>
#include <memory>
#include <string>
#include <vector>

// Generated by reflectgen at build time (see reflection.md's "Automatic
// CMake integration"), compiled straight into newui.lib - but calling it
// is still up to application startup code (same as shapes1.cpp/shapes2.cpp/
// src/main.cpp already do), not automatic just from linking against
// newui. ListController::createItem() (controllers.h) constructs its
// ListItem via reflection::classinfo("ListItem")->createInstance() -
// without this call, that lookup fails and every row silently comes back
// null, which ListView::paint() (controls.h) just as silently skips: a
// real, confirmed live bug this exact demo hit (nothing rendered, no
// crash, no error at all) before this call was added - see HANDOFF.md.
extern void registerReflectionData();

newui::SyncReturn FrameClosed(newui::Frame& frame) {
    printf("Frame (%p, hwnd: %p) closed, exiting application.\n", &frame, frame.frameHandle());
    return newui::SyncReturn::Handled;
}

// A minimal real Model: a flat list of strings, addressed by the
// std::size_t index ListController/ListItem already expect - ListItem::
// paint() (items.cpp) reads value(index) back via
// std::any_cast<std::string>(), so a real Model's value() needs to hand
// back a std::string (not std::wstring) for the built-in row rendering
// to actually show text. size() is the one piece of information
// items-plan.md's Item/Controller design needed from a concrete Model
// that the base Model class itself can't generically answer (models.h).
//
// Derives from ListModel (models.h), not plain Model - ListController::
// setModel() (controllers.h) requires it specifically, a compile-time
// guarantee that whatever's attached to a ListView is genuinely list-
// shaped.
class StringListModel : public newui::ListModel {
public:
    std::vector<std::string> rows;

    std::any value(const std::any& key) override {
        if (const std::size_t* index = std::any_cast<std::size_t>(&key)) {
            if (*index < rows.size()) {
                return rows[*index];
            }
        }
        return std::any();
    }

    std::size_t size() const override {
        return rows.size();
    }
};

// A minimal real TreeModel (models.h), backed by a std::map<path,
// children> - a more typical real-world shape than a hand-rolled tree of
// node structs: childrenByParent maps a parent path (empty = the root)
// to the ordered labels of its own direct children, so path {0,2}'s own
// label lives at childrenByParent[{0}][2]. A path with no entry in the
// map (never populated, or genuinely a leaf) just has 0 children -
// childCount() and value() both fall through to that case the same way.
class StringTreeModel : public newui::TreeModel {
public:
    std::map<std::vector<std::size_t>, std::vector<std::string>> childrenByParent;

    std::size_t childCount(const std::vector<std::size_t>& path) const override {
        auto it = childrenByParent.find(path);
        return it != childrenByParent.end() ? it->second.size() : 0;
    }

    std::any value(const std::any& key) override {
        if (const std::vector<std::size_t>* path = std::any_cast<std::vector<std::size_t>>(&key)) {
            if (!path->empty()) {
                std::vector<std::size_t> parentPath(path->begin(), path->end() - 1);
                std::size_t lastIndex = path->back();
                auto it = childrenByParent.find(parentPath);
                if (it != childrenByParent.end() && lastIndex < it->second.size()) {
                    return it->second[lastIndex];
                }
            }
        }
        return std::any();
    }
};

// Class name (via reflection, the same reflection::classinfo() lookup
// ItemController::instantiateItem() uses internally, controllers.cpp -
// typeid(view) gives View's real dynamic type since it's polymorphic)
// plus name() (if set) plus this View's own address - the same "%p"
// convention FrameClosed() above already uses, so two views of the same
// class are still told apart at a glance.
std::string describeView(const newui::View& view) {
    const newui::reflection::Class* cls = newui::reflection::classinfo(typeid(view));
    std::string className = cls != nullptr ? cls->name() : "View";

    char buf[256];
    if (view.name().empty()) {
        std::snprintf(buf, sizeof(buf), "%s (%p)", className.c_str(), static_cast<const void*>(&view));
    } else {
        std::snprintf(buf, sizeof(buf), "%s \"%s\" (%p)", className.c_str(), view.name().c_str(), static_cast<const void*>(&view));
    }
    return std::string(buf);
}

// A TreeModel over the REAL live View hierarchy (view.h) - not synthetic
// test data: the exact same childViews() tree RootView::repaint()/
// View::paintChildren() (rootview.cpp/view.h) already walk to draw the
// whole app. Path {0} is rootView itself (this model's one top-level
// node - "empty path = the invisible super-root's own children",
// TreeModel's own convention, models.h, has exactly one child here);
// path {0, i, j, ...} walks childViews()[i]->childViews()[j]->... from
// there.
class ViewTreeModel : public newui::TreeModel {
public:
    newui::RootView* rootView = nullptr;

    newui::View* resolveView(const std::vector<std::size_t>& path) const {
        if (rootView == nullptr || path.empty()) {
            return nullptr;
        }
        newui::View* view = rootView;  // path[0] == 0 selects rootView itself
        for (std::size_t i = 1; i < path.size(); ++i) {
            const std::vector<newui::SubView*>& children = view->childViews();
            std::size_t index = path[i];
            if (index >= children.size()) {
                return nullptr;
            }
            view = children[index];
        }
        return view;
    }

    std::size_t childCount(const std::vector<std::size_t>& path) const override {
        if (path.empty()) {
            return rootView != nullptr ? 1 : 0;
        }
        newui::View* view = resolveView(path);
        return view != nullptr ? view->childViews().size() : 0;
    }

    std::any value(const std::any& key) override {
        if (const std::vector<std::size_t>* path = std::any_cast<std::vector<std::size_t>>(&key)) {
            newui::View* view = resolveView(*path);
            if (view != nullptr) {
                return describeView(*view);
            }
        }
        return std::any();
    }
};

int main() {
    registerReflectionData();

    std::cout << "newui " << newui::version() << " - MVC example\n";
    std::cout << "A ListView and a TreeView, each driven by a real Model.\n";
    std::cout << "Click a row to select it; click a tree node's glyph to expand/collapse it.\n";

    newui::Frame frame;

    newui::Application& app = newui::Application::instance();
    app.setName("mvc1");
    app.setFrame(&frame);

    frame.setTitle("MVC Example");
    frame.setBounds(newui::Rect(10, 10, 480, 940));
    frame.onClosed += FrameClosed;

    newui::RootView& root = frame.rootView();
    // UIColorManager::colorFor(), not a hardcoded literal - see
    // controls1.cpp's own MakeLabel()/main() for why: this toolkit's
    // native controls already track Windows' OS-level Light/Dark mode
    // setting on their own, so this demo's own app-drawn background needs
    // to track the same setting or the two drift out of sync.
    root.style().setBackgroundColor(newui::UIColorManager::colorFor(newui::UIColorRole::WindowBackground));

    auto rootLayout = std::make_unique<newui::FlexLayout>(newui::Orientation::Vertical);
    rootLayout->setSpacing(10.0f);
    rootLayout->setPadding(16.0f);
    root.setLayout(std::move(rootLayout));

    // The Model - seeded with enough rows that the list genuinely
    // overflows its own viewport, so the ScrollView below actually has
    // something to scroll. Declared here in main() (not static) - stays
    // alive for app.run()'s whole duration, same as every other local in
    // this function.
    StringListModel model;
    for (int i = 0; i < 40; ++i) {
        model.rows.push_back("Row " + std::to_string(i));
    }

    // ListView hosted inside a ScrollView - same virtualized-child
    // pattern controls1.cpp's own TextControl section already uses:
    // ScrollView detects listView answers onQueryContentSize (view.h),
    // provides the real scrollbar, and pins listView's own bounds to the
    // viewport instead of growing them to the full content height.
    auto* listViewScrollView = new newui::ScrollView();
    listViewScrollView->setLayoutParams(std::make_unique<newui::FlexLayoutParams>(1.0f));
    root.addChild(listViewScrollView);

    auto* listView = new newui::ListView();
    listView->setModel(&model);
    listViewScrollView->addChild(listView);

    // A plain Label listing every currently selected row - a real,
    // visible proof that click -> ListView::setSelectedIndex()/
    // toggleSelection()/selectRange() -> onSelectionChanged ->
    // Model::value(index) all actually work end to end, not just that
    // the rows paint. Try a plain click (replaces the selection),
    // Ctrl+click (toggles one row without disturbing the rest), and
    // Shift+click (selects the range from the last plain/Ctrl+click).
    auto* selectionLabel = new newui::Label();
    selectionLabel->setText("(nothing selected)");
    selectionLabel->setDesiredSize(newui::Size(0.0f, 24.0f));
    root.addChild(selectionLabel);

    listView->onSelectionChanged.add([selectionLabel](newui::ListView& sender) {
        if (sender.selectedIndices().empty()) {
            selectionLabel->setText("(nothing selected)");
            return newui::SyncReturn::Handled;
        }

        std::string text = "Selected: ";
        bool first = true;
        for (std::size_t index : sender.selectedIndices()) {
            std::any value = sender.model()->value(index);
            if (const std::string* rowText = std::any_cast<std::string>(&value)) {
                if (!first) {
                    text += ", ";
                }
                text += *rowText;
                first = false;
            }
        }
        selectionLabel->setText(text);
        return newui::SyncReturn::Handled;
        });

    // TreeView hosted inside its own ScrollView, same virtualized-child
    // pattern as listView above - a small folder/file StringTreeModel to
    // exercise expand/collapse (click a node's own glyph), indentation,
    // and multi-selection over tree paths (TreeView::selectedPaths()).
    StringTreeModel treeModel;
    treeModel.childrenByParent[{}] = { "Documents", "Pictures", "Downloads" };
    treeModel.childrenByParent[{ 0u }] = { "Resume.docx", "Notes.txt", "Projects" };
    treeModel.childrenByParent[{ 0u, 2u }] = { "newui", "old-project" };
    treeModel.childrenByParent[{ 1u }] = { "vacation.jpg", "family.png" };
    // "Downloads" ({2}) has no entry at all - childCount() falls through
    // to 0, same as a genuine leaf.

    auto* treeViewScrollView = new newui::ScrollView();
    treeViewScrollView->setLayoutParams(std::make_unique<newui::FlexLayoutParams>(1.0f));
    root.addChild(treeViewScrollView);

    auto* treeView = new newui::TreeView();
    treeView->setModel(&treeModel);
    treeViewScrollView->addChild(treeView);

    auto* treeSelectionLabel = new newui::Label();
    treeSelectionLabel->setText("(nothing selected)");
    treeSelectionLabel->setDesiredSize(newui::Size(0.0f, 24.0f));
    root.addChild(treeSelectionLabel);

    treeView->onSelectionChanged.add([treeSelectionLabel](newui::TreeView& sender) {
        if (sender.selectedPaths().empty()) {
            treeSelectionLabel->setText("(nothing selected)");
            return newui::SyncReturn::Handled;
        }

        std::string text = "Selected: ";
        bool first = true;
        for (const std::vector<std::size_t>& path : sender.selectedPaths()) {
            std::any value = sender.model()->value(path);
            if (const std::string* label = std::any_cast<std::string>(&value)) {
                if (!first) {
                    text += ", ";
                }
                text += *label;
                first = false;
            }
        }
        treeSelectionLabel->setText(text);
        return newui::SyncReturn::Handled;
        });

    // DropDownList - a single-selection combo box built on the same
    // ListController/ListModel/ListItem/ListView foundation as the plain
    // ListView above, just with its list hosted in a PopupFrame
    // (popupframe.h) instead of an always-visible ScrollView. Click the
    // arrow button on the right to drop the list down; click a row to
    // select it and close the popup; click the button again (or anywhere
    // outside the popup) to dismiss it without changing the selection.
    StringListModel colorModel;
    colorModel.rows = { "Red", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet" };

    auto* dropDown = new newui::DropDownList();
    dropDown->setModel(&colorModel);
    dropDown->setDesiredSize(newui::Size(0.0f, 24.0f));
    root.addChild(dropDown);

    auto* dropDownSelectionLabel = new newui::Label();
    dropDownSelectionLabel->setText("(nothing selected)");
    dropDownSelectionLabel->setDesiredSize(newui::Size(0.0f, 24.0f));
    root.addChild(dropDownSelectionLabel);

    dropDown->onSelectionChanged.add([dropDownSelectionLabel](newui::DropDownList& sender) {
        if (!sender.selectedIndex().has_value()) {
            dropDownSelectionLabel->setText("(nothing selected)");
            return newui::SyncReturn::Handled;
        }
        std::any value = sender.model()->value(*sender.selectedIndex());
        if (const std::string* label = std::any_cast<std::string>(&value)) {
            dropDownSelectionLabel->setText("Selected: " + *label);
        }
        return newui::SyncReturn::Handled;
        });

    // TreeView showing the REAL live View hierarchy of this very window,
    // root on down - built last, after everything else above, so its own
    // snapshot already includes every SubView already added (right down
    // to itself, once added below - a real, honest "everything currently
    // in this window" browser, not a synthetic example). rootView's own
    // node starts expanded (setExpanded()) so its direct children are
    // immediately visible without an extra click.
    ViewTreeModel viewTreeModel;
    viewTreeModel.rootView = &root;

    auto* viewTreeScrollView = new newui::ScrollView();
    viewTreeScrollView->setLayoutParams(std::make_unique<newui::FlexLayoutParams>(1.0f));
    root.addChild(viewTreeScrollView);

    auto* viewTreeView = new newui::TreeView();
    viewTreeView->setModel(&viewTreeModel);
    viewTreeView->controller().setExpanded(std::vector<std::size_t>{ 0u }, true);
    viewTreeScrollView->addChild(viewTreeView);

    auto* viewTreeSelectionLabel = new newui::Label();
    viewTreeSelectionLabel->setText("(nothing selected)");
    viewTreeSelectionLabel->setDesiredSize(newui::Size(0.0f, 24.0f));
    root.addChild(viewTreeSelectionLabel);

    viewTreeView->onSelectionChanged.add([viewTreeSelectionLabel](newui::TreeView& sender) {
        if (sender.selectedPaths().empty()) {
            viewTreeSelectionLabel->setText("(nothing selected)");
            return newui::SyncReturn::Handled;
        }

        std::string text = "Selected: ";
        bool first = true;
        for (const std::vector<std::size_t>& path : sender.selectedPaths()) {
            std::any value = sender.model()->value(path);
            if (const std::string* label = std::any_cast<std::string>(&value)) {
                if (!first) {
                    text += ", ";
                }
                text += *label;
                first = false;
            }
        }
        viewTreeSelectionLabel->setText(text);
        return newui::SyncReturn::Handled;
        });

    app.run();

    return 0;
}
